# Merge Sort and Quick Sort

# 0-1 Knapsack 

In [2]:
import numpy as np

class Knapsack():
    def __init__(self,capacity,profit,weight):
        self.n=len(profit)
        self.profit=profit
        self.weight=weight
        self.a1=self.recursion(capacity,0,0)
        print("Via recursion",self.a1)
        self.dp=np.zeros(self.n+1,capacity+1)
        self.a2=self.memoise(capacity,0)
        print("via memoisation",self.a2)
        
    def recursion(self,capacity,i,amt):
        #base cases
        if(i==self.n):
            return amt
        if(capacity==0):
            return amt
        else:
            val2=self.recursion(capacity,i+1,amt)
            val1=0
            if(capacity-self.weight[i]>=0):
                capacity=capacity-self.weight[i]
                amt+=self.profit[i]
                val1=self.recursion(capacity,i+1,amt)
            return max(val1,val2)
        
    def memoise(self,capacity,i):
        #base case
        if(self.dp[self.n][capacity]!=0):
            return self.dp[self.n][capacity]
        val2=self.dp
            
            
            
        
                
                
            

profit= [60,100,120]
weight = [10,20,30]
capacity=50
case1=Knapsack(capacity,profit,weight)
case1.a1

Via recursion 220


TypeError: Cannot interpret '51' as a data type

# N queens

In [1]:
import numpy as np

class Nqueens():
    def __init__(self,n):
        self.n=n
        self.board=np.zeros((n,n))
        self.col=np.zeros(n)
        self.row=np.zeros(n)
        self.diag1=np.zeros(2*n)
        self.diag2=np.zeros(2*n)
        self.res=[]
        self.backtrack(0)
        
    def print_state(self):
        print("board \n",self.board)
        print("\n col \n",self.col)
        print("\n row \n",self.row)
        print("\n diag1 \n",self.diag1)
        print("\n diag2 \n",self.diag2)
        
    def test(self,i,j): #test returns True if we can place a queen on that cell
        diff=(i-j)+(self.n-1)
        summ=i+j
        if(self.board[i][j]==1):
            return False
        elif(self.col[j]==1):
            return False
        elif(self.row[i]==1):
            return False
        elif(self.diag1[diff]==1):
            return False
        elif(self.diag2[summ]==1):
            return False
        else:
            return True
        
    def fill(self,i,j,t): # pass 0 to unfill and pass 1 to fill
        diff=(i-j)+(self.n-1)
        summ=i+j
        self.board[i][j]=t
        self.row[i]=t
        self.col[j]=t
        self.diag1[diff]=t
        self.diag2[summ]=t
        
    def backtrack(self,r):
        #we have got the result when r=n
        if(r==self.n):
            snapshot=self.board.copy()
            self.res.append(snapshot)
            return
        else:
            for j in range(self.n):
                if(self.test(r,j)==True):
                    self.fill(r,j,1)
                    self.backtrack(r+1)
                    self.fill(r,j,0)
                    
case1=Nqueens(8)
print(f"\n Printing the {len(case1.res)} matrices from result board")
for m in case1.res:
    print(m)
    print("\n")



 Printing the 92 matrices from result board
[[1. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 1. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 1.]
 [0. 0. 0. 0. 0. 1. 0. 0.]
 [0. 0. 1. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 1. 0.]
 [0. 1. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 1. 0. 0. 0. 0.]]


[[1. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 1. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 1.]
 [0. 0. 1. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 1. 0.]
 [0. 0. 0. 1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 1. 0. 0. 0.]]


[[1. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 1. 0.]
 [0. 0. 0. 1. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 1. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 1.]
 [0. 1. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0. 0. 0. 0.]]


[[1. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 1.]
 [0. 1. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 1. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 1. 0. 0.]
 [0. 0. 1. 0. 0. 0. 0. 0.]]


[[0. 1. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 1. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 1. 0. 0.

# TSP using Branch and Bound

In [ ]:
import numpy as np
from copy import deepcopy 

class TSP():
    def __init__(self,dist):
        self.rows=len(dist)
        self.cols=len(dist[0])
        self.dist=dist
        self.bnb()
    
    def display(self,m):
        print("\n")
        for x in m:
            print(x)
    
    def reduce(self,m):
        reduction_cost=0
        for i in range(self.rows):
            lv=np.inf
            for j in range(self.cols):
                lv=min(lv,m[i][j])
            if(lv==np.inf):
                continue
            reduction_cost+=lv
            
            for j in range(self.cols):
                m[i][j]-=lv
        for j in range(self.cols):
            lv=np.inf
            for i in range(self.rows):
                lv=min(lv,m[i][j])
            if(lv==np.inf):
                continue
            reduction_cost+=lv
            
            for i in range(self.rows):
                m[i][j]-=lv
        
        print("cost ",reduction_cost)
        return reduction_cost
        
    def make_inf(self,m,i,j):
        m[i][j]=np.inf
        m[j][i]=np.inf
        for r in range(self.rows):
            m[r][j]=np.inf
        for c in range(self.cols):
            m[i][c]=np.inf
        
    def generate_child_cost(self,temp,parent,i,j):
        
        val=temp[i][j]
        self.make_inf(temp,i,j)
        self.display(temp)
        cost=self.reduce(temp)+val+parent
        print(f"Generated cost for edge {i},{j} is : {cost}")
        return cost
    
    def obtain_level_wise_least_cost(self,m,parent,cost):
        # generate edge
        future=-1
        lc=np.inf
        next_gen_parent=m
        for nodes in range(0,self.cols):
            if(m[parent][nodes]==np.inf):
                continue
            temp=deepcopy(m)
            child_cost=self.generate_child_cost(temp,cost,parent,nodes)
            if(child_cost<lc):
                future=nodes
                lc=child_cost
                next_gen_parent=temp
        print("least cost branch and bound ",lc)
        return future,lc,next_gen_parent
    
    def bnb(self):
        upper=np.inf
        m=deepcopy(self.dist)
        self.display(m)
        cost=self.reduce(m)
        
        print("Level 1")
        parent,cost,next_gen_parent=self.obtain_level_wise_least_cost(m,0,cost)
        print(f" Level 1 ends parent {parent} cost {cost} and next generation parent being")
        display(next_gen_parent)
        print("Level 2")
        parent,cost,next_gen_parent=self.obtain_level_wise_least_cost(next_gen_parent,parent,cost)
        print(f" Level 2 ends parent {parent} cost {cost} and next generation parent being")
        display(next_gen_parent)
        print("Level 3")
        
        parent,cost,next_gen_parent=self.obtain_level_wise_least_cost(next_gen_parent,parent,cost)
        print(f" Level 3 ends parent {parent} cost {cost} and next generation parent being")
        display(next_gen_parent)
        print("Level 4")
        
        
        
            
        
        
        
        
        
        

dist=[[np.inf,20,30,10,11],[15,np.inf,16,4,2],[3,5,np.inf,2,4],[19,6,18,np.inf,3],[16,4,7,16,np.inf]]
m1=TSP(dist)


least cost incured:  35
chosen path  (0, 3, 9, 4, 2, 1, 8, 6, 5, 7)


# TSP using genetic

# Matrix Multiplication

# Extras


## Tsp using Permutation and Combination

In [ ]:
from copy import deepcopy
import numpy as np
import itertools

def p2(ip):
    mainline=list(itertools.permutations(ip))
    return mainline


        

def generate(n):
    cities=[]
    for x in range(n):
        cities.append(x)
    op=[]
    mainline=[]
    n=len(cities)
    mainline=p2(cities)
    return mainline
    
    
def solve(dist):
    n=len(dist)
    mainline=generate(n)
    lc=np.inf
    chosen_path=[]
    for tup in mainline:
        cost=0
        for j in range(n-1):
            s=tup[j]
            d=tup[j+1]
            curr=dist[s][d]
            cost+=curr
            if(curr==np.inf):
                break
        j+=1
        s=tup[j]
        d=tup[0]
        cost+=dist[s][d]
        if(cost<lc):
            chosen_path=tup
            lc=cost
    print("least cost incured: ",lc)
    print("chosen path ",chosen_path)
        

m=[[np.inf,14,12,1,11,12,19,4,20,16],
[14,np.inf,9,2,13,15,17,5,2,19],
[12,9,np.inf,6,2,15,14,11,3,19],
[1,2,6,np.inf,9,13,2,2,19,2],
[11,13,2,9,np.inf,7,18,9,4,6],
[12,15,15,13,7,np.inf,4,4,20,7],
[19,17,14,2,18,4,np.inf,15,1,8],
[4,5,11,2,9,4,15,np.inf,11,17],
[20,2,3,19,4,20,1,11,np.inf,20],
[16,19,19,2,6,7,8,17,20,np.inf]]  

#dist=[[np.inf,20,30,10,11],[15,np.inf,16,4,2],[3,5,np.inf,2,4],[19,6,18,np.inf,3],[16,4,7,16,np.inf]]

solve(m)




## TSP using Dynamic Programing